server:
  port: 8023

  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 100
      min-spare: 30
    # 最大吞吐量不限制
    max-swallow-size: -1
  # 优雅停机 关闭容器后默认等待30秒继续执行没处理完的任务 避免数据不一致
  shutdown: graceful

spring:
  application:
    name: csYun
  profiles:
    active: yun
  datasource:
    dynamic:
      #      primary: yun
      #      seata: true
      datasource:
        master:
          driver-class-name: com.mysql.cj.jdbc.Driver
          url: jdbc:mysql://120.26.13.162:3306/auth?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
          username: root
          password: syp8023

# Mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    #    日志控制台打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# PageHelper分页插件
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql

# Swagger配置
swagger:
  # 是否开启swagger
  enabled: true
  # 请求前缀
  pathMapping: /dev-api

redis:
  enabled: true
  host: 120.26.13.162
  port: 6379
  timeout: 2000
  password: 199501
  # 默认0,第一个
  database: 0
  pool:
    minIdle: 1
    maxIdle: 10
    maxWait: 3
    maxActive: 8